/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gepwhrotbupiypuudupu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlcHdocm90YnVwaXlwdXVkdXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNTAyOTAsImV4cCI6MjA4OTkyNjI5MH0.Azhr2fZ66I-BzVEGCzD6LKYiwuF-yS_2tYuZDXO47v8"